# permissions for end users to edit pongs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pong-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pong-operator
    app.kubernetes.io/part-of: pong-operator
    app.kubernetes.io/managed-by: kustomize
  name: pong-editor-role
rules:
- apiGroups:
  - games.fredericbarrau.bzh
  resources:
  - pongs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.fredericbarrau.bzh
  resources:
  - pongs/status
  verbs:
  - get
