---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - games.fredericbarrau
  resources:
  - pongs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.fredericbarrau
  resources:
  - pongs/finalizers
  verbs:
  - update
- apiGroups:
  - games.fredericbarrau
  resources:
  - pongs/status
  verbs:
  - get
  - patch
  - update
